name: baqaala
description: Grocery Delivery Application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.8+108

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  provider: ^4.3.2

  flutter_spinkit: ^4.1.2+1

  uuid: ^2.2.2

  mask_text_input_formatter: ^1.0.7

  flutter_credit_card: ^0.1.3

  font_awesome_flutter: ^8.8.1

  back_button_interceptor: ^4.3.0

  flutter_webview_plugin: ^0.3.11

  crypto: ^2.1.5

  slugify2: ^0.2.1

  image_picker: ^0.6.7+4

  responsive_flutter: ^0.0.4

  image_cropper: ^1.3.0

  flutter_native_image: ^0.0.5+2

  # secure_application: ^3.5.3

  # flutter_windowmanager: ^0.0.2

  audioplayers: ^0.15.1

  google_fonts: ^1.1.0

  # flash: "^1.3.1"

  timeago: ^2.0.26

  algolia: ^0.1.7

  validate: ^1.7.0

  flutter_svg: ^0.19.3

  blurhash: ^0.2.0

  transparent_image: ^1.0.0

  share: ^0.6.4+5

  # flutter_tagging: ^2.2.0+3

  get: ^3.4.6

  flutter_statusbarcolor: ^0.2.3

  barcode_scan: ^3.0.1

  google_maps_webservice: ^0.0.18

  firebase_messaging: ^6.0.16

  firebase_core: ^0.4.5

  firebase_auth: ^0.16.1

  firebase_analytics: ^5.0.16

  firebase_storage: ^3.1.6

  cloud_firestore: ^0.13.7

  shared_preferences: ^0.5.8

  flutter_slidable: ^0.5.5

  connectivity: ^0.4.9

  localstorage: ^3.0.2+5

  google_maps_flutter: ^0.5.30

  # google_map_polyutil: ^1.0.0

  url_launcher: ^5.5.0

#  intl: ^0.16.1

  easy_localization: ^2.0.0

  lottie: ^0.5.1

  excel: ^1.1.4

  animated_text_kit: ^2.2.0

  after_layout: ^1.0.7+2

  sms_autofill: ^1.2.3

  cloud_functions: ^0.5.0

  cached_network_image: ^2.2.0+1

  geolocator: ^5.3.2+2

  background_location: ^0.1.2

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/lottie/
    - assets/images/
    - assets/sounds/
    - assets/categories/
    - assets/baby-products.xlsx
    - assets/beverages.xlsx
    - assets/breakfast.xlsx
    - assets/canned-items.xlsx
    - assets/snacks.xlsx
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
